openapi: 3.0.3
info:
  title: MatrixCalc API
  description: Calculate expression with matrix
  version: 1.0.0
servers:
  - url: https://localhost/
paths:
  /calculate:
    post:
      summary: "Calculate expression"
      parameters:
        -
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  placeholder:
                    type: token
                    description: Placeholder description

        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found

components:
  schemas:
    200:
      title: token
      properties:
        type:
          title: id
          type: enum

