# TODO add require field
openapi: 3.0.0
info:
  title: MatrixCalc API
  description: Calculate expression with matrix
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /calculate:
    post:
      tags:
        - Calculate
      summary: "Calculate expression"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expression:
                  type: string
                  example: '3*X'
                variables:
                  type: array
                  items:
                    $ref: '#/components/schemas/variable'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  status:

                    enum:
                      - ok
                      - error
                  result:
                    $ref: '#/components/schemas/variable'
                  details:
                    type: string
components:
  schemas:
    variable:
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - matrix
            - fraction
        value:
          anyOf:
            - $ref: '#/components/schemas/matrix'
            - $ref: '#/components/schemas/fraction'
    fraction:
      properties:
        numerator:
          type: integer
        denominator:
          type: integer
      example:
        numerator: 5
        denominator: -2
    matrix:
      properties:
        main:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/fraction'
        augmented:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/fraction'



